In [1]:
import numpy as np
import pandas as pd
# ^^^ pyforest auto-imports - don't write above this line
import pandas as pd

# Data Cleaning

- `isna()` --> retorna uma máscara booleana que vai ser True onde o valor for missing.
- `fillna()` --> completa os missings com o argumento que você colocar (retorna um dataframe)
- `duplicated()` --> retorna True se for duplicado (por default, True a partir da segunda repetição)
- `drop_duplicates()` --> remove as linhas duplicadas (remove as linhas que o `duplicated()` retorna True)

- Mascaras na verdade nada mais são do que Series ou DataFrames - por isso conseguimos trabalhar neles da mesma forma, inclusive criando novas máscaras a partir deles - por exemplo quando usamos:

```python
mask = vehicles.isna()

vehicles.loc[mask.mean() < 0.8, :]

```

# Read DataFrame

Description: 

http://lib.stat.cmu.edu/datasets/sleep

In [3]:
animals = pd.read_csv('http://www.statsci.org/data/general/sleep.txt', sep='\t')

In [4]:
animals.head()

,Species,BodyWt,BrainWt,NonDreaming,Dreaming,TotalSleep,LifeSpan,Gestation,Predation,Exposure,Danger
0,Africanelephant,6654.000,5712.0,NaN,NaN,3.3,38.6,645.0,3,5,3
1,Africangiantpouchedrat,1.000,6.6,6.3,2.0,8.3,4.5,42.0,3,1,3
2,ArcticFox,3.385,44.5,NaN,NaN,12.5,14.0,60.0,1,1,1
3,Arcticgroundsquirrel,0.920,5.7,NaN,NaN,16.5,NaN,25.0,5,2,3
4,Asianelephant,2547.000,4603.0,2.1,1.8,3.9,69.0,624.0,3,5,4

In [5]:
animals.describe()

,BodyWt,BrainWt,NonDreaming,Dreaming,TotalSleep,LifeSpan,Gestation,Predation,Exposure,Danger
count,62.000000,62.000000,48.000000,50.000000,58.000000,58.000000,58.000000,62.000000,62.000000,62.000000
mean,198.789984,283.134194,8.672917,1.972000,10.532759,19.877586,142.353448,2.870968,2.419355,2.612903
std,899.158011,930.278942,3.666452,1.442651,4.606760,18.206255,146.805039,1.476414,1.604792,1.441252
min,0.005000,0.140000,2.100000,0.000000,2.600000,2.000000,12.000000,1.000000,1.000000,1.000000
25%,0.600000,4.250000,6.250000,0.900000,8.050000,6.625000,35.750000,2.000000,1.000000,1.000000
50%,3.342500,17.250000,8.350000,1.800000,10.450000,15.100000,79.000000,3.000000,2.000000,2.000000
75%,48.202500,166.000000,11.000000,2.550000,13.200000,27.750000,207.500000,4.000000,4.000000,4.000000
max,6654.000000,5712.000000,17.900000,6.600000,19.900000,100.000000,645.000000,5.000000,5.000000,5.000000

In [6]:
animals['nova_coluna'] = 3

In [7]:
animals

,Species,BodyWt,BrainWt,NonDreaming,Dreaming,TotalSleep,LifeSpan,Gestation,Predation,Exposure,Danger,nova_coluna
0,Africanelephant,6654.000,5712.0,NaN,NaN,3.3,38.6,645.0,3,5,3,3
1,Africangiantpouchedrat,1.000,6.6,6.3,2.0,8.3,4.5,42.0,3,1,3,3
2,ArcticFox,3.385,44.5,NaN,NaN,12.5,14.0,60.0,1,1,1,3
3,Arcticgroundsquirrel,0.920,5.7,NaN,NaN,16.5,NaN,25.0,5,2,3,3
4,Asianelephant,2547.000,4603.0,2.1,1.8,3.9,69.0,624.0,3,5,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...
57,Treehyrax,2.000,12.3,4.9,0.5,5.4,7.5,200.0,3,1,3,3
58,Treeshrew,0.104,2.5,13.2,2.6,15.8,2.3,46.0,3,2,2,3
59,Vervet,4.190,58.0,9.7,0.6,10.3,24.0,210.0,4,3,4,3
60,Wateropossum,3.500,3.9,12.8,6.6,19.4,3.0,14.0,2,1,1,3
61,Yellow-belliedmarmot,4.050,17.0,NaN,NaN,NaN,13.0,38.0,3,1,1,3

# DataFrame Calculations

## Performing calculations to create a new column

### Using constants

In [10]:
animals['nova_coluna'] = 1

In [11]:
animals

,Species,BodyWt,BrainWt,NonDreaming,Dreaming,TotalSleep,LifeSpan,Gestation,Predation,Exposure,Danger,nova_coluna,nome_coluna
0,Africanelephant,6654.000,5712.0,NaN,NaN,3.3,38.6,645.0,3,5,3,1,1
1,Africangiantpouchedrat,1.000,6.6,6.3,2.0,8.3,4.5,42.0,3,1,3,1,1
2,ArcticFox,3.385,44.5,NaN,NaN,12.5,14.0,60.0,1,1,1,1,1
3,Arcticgroundsquirrel,0.920,5.7,NaN,NaN,16.5,NaN,25.0,5,2,3,1,1
4,Asianelephant,2547.000,4603.0,2.1,1.8,3.9,69.0,624.0,3,5,4,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,Treehyrax,2.000,12.3,4.9,0.5,5.4,7.5,200.0,3,1,3,1,1
58,Treeshrew,0.104,2.5,13.2,2.6,15.8,2.3,46.0,3,2,2,1,1
59,Vervet,4.190,58.0,9.7,0.6,10.3,24.0,210.0,4,3,4,1,1
60,Wateropossum,3.500,3.9,12.8,6.6,19.4,3.0,14.0,2,1,1,1,1
61,Yellow-belliedmarmot,4.050,17.0,NaN,NaN,NaN,13.0,38.0,3,1,1,1,1

In [20]:
animals.columns = [col.lower() for col in animals.columns]

In [25]:
animals['bodywt'] * 2.205

0     14672.070000
1         2.205000
2         7.463925
3         2.028600
4      5616.135000
          ...
57        4.410000
58        0.229320
59        9.238950
60        7.717500
61        8.930250
Name: bodywt, Length: 62, dtype: float64

In [26]:
# from kggrams to pounds
animals['bodywt_pounds'] = animals['bodywt'] * 2.205

In [27]:
animals

,species,bodywt,brainwt,nondreaming,dreaming,totalsleep,lifespan,gestation,predation,exposure,danger,nova_coluna,nome_coluna,bodywt_pounds
0,Africanelephant,6654.000,5712.0,NaN,NaN,3.3,38.6,645.0,3,5,3,1,1,14672.070000
1,Africangiantpouchedrat,1.000,6.6,6.3,2.0,8.3,4.5,42.0,3,1,3,1,1,2.205000
2,ArcticFox,3.385,44.5,NaN,NaN,12.5,14.0,60.0,1,1,1,1,1,7.463925
3,Arcticgroundsquirrel,0.920,5.7,NaN,NaN,16.5,NaN,25.0,5,2,3,1,1,2.028600
4,Asianelephant,2547.000,4603.0,2.1,1.8,3.9,69.0,624.0,3,5,4,1,1,5616.135000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,Treehyrax,2.000,12.3,4.9,0.5,5.4,7.5,200.0,3,1,3,1,1,4.410000
58,Treeshrew,0.104,2.5,13.2,2.6,15.8,2.3,46.0,3,2,2,1,1,0.229320
59,Vervet,4.190,58.0,9.7,0.6,10.3,24.0,210.0,4,3,4,1,1,9.238950
60,Wateropossum,3.500,3.9,12.8,6.6,19.4,3.0,14.0,2,1,1,1,1,7.717500
61,Yellow-belliedmarmot,4.050,17.0,NaN,NaN,NaN,13.0,38.0,3,1,1,1,1,8.930250

In [28]:
# from grams to kg
animals['brainwt_kg'] = animals['brainwt'] / 1000

In [29]:
animals.head()

,species,bodywt,brainwt,nondreaming,dreaming,totalsleep,lifespan,gestation,predation,exposure,danger,nova_coluna,nome_coluna,bodywt_pounds,brainwt_kg
0,Africanelephant,6654.000,5712.0,NaN,NaN,3.3,38.6,645.0,3,5,3,1,1,14672.070000,5.7120
1,Africangiantpouchedrat,1.000,6.6,6.3,2.0,8.3,4.5,42.0,3,1,3,1,1,2.205000,0.0066
2,ArcticFox,3.385,44.5,NaN,NaN,12.5,14.0,60.0,1,1,1,1,1,7.463925,0.0445
3,Arcticgroundsquirrel,0.920,5.7,NaN,NaN,16.5,NaN,25.0,5,2,3,1,1,2.028600,0.0057
4,Asianelephant,2547.000,4603.0,2.1,1.8,3.9,69.0,624.0,3,5,4,1,1,5616.135000,4.6030

# Performing calculations using columns

In [34]:
# get the ratio between brain and body.
animals['ratio_brain_body'] = animals['brainwt'] / animals['bodywt']

In [35]:
# careful with scales!!
animals.head()

,species,bodywt,brainwt,nondreaming,dreaming,totalsleep,lifespan,gestation,predation,exposure,danger,nova_coluna,nome_coluna,bodywt_pounds,brainwt_kg,ratio_brain_body
0,Africanelephant,6654.000,5712.0,NaN,NaN,3.3,38.6,645.0,3,5,3,1,1,14672.070000,5.7120,0.858431
1,Africangiantpouchedrat,1.000,6.6,6.3,2.0,8.3,4.5,42.0,3,1,3,1,1,2.205000,0.0066,6.600000
2,ArcticFox,3.385,44.5,NaN,NaN,12.5,14.0,60.0,1,1,1,1,1,7.463925,0.0445,13.146233
3,Arcticgroundsquirrel,0.920,5.7,NaN,NaN,16.5,NaN,25.0,5,2,3,1,1,2.028600,0.0057,6.195652
4,Asianelephant,2547.000,4603.0,2.1,1.8,3.9,69.0,624.0,3,5,4,1,1,5616.135000,4.6030,1.807224

In [36]:
# get the ratio between brain and body.
animals['ratio_brain_body'] = animals['brainwt_kg'] / animals['bodywt']

In [37]:
animals.head()

,species,bodywt,brainwt,nondreaming,dreaming,totalsleep,lifespan,gestation,predation,exposure,danger,nova_coluna,nome_coluna,bodywt_pounds,brainwt_kg,ratio_brain_body
0,Africanelephant,6654.000,5712.0,NaN,NaN,3.3,38.6,645.0,3,5,3,1,1,14672.070000,5.7120,0.000858
1,Africangiantpouchedrat,1.000,6.6,6.3,2.0,8.3,4.5,42.0,3,1,3,1,1,2.205000,0.0066,0.006600
2,ArcticFox,3.385,44.5,NaN,NaN,12.5,14.0,60.0,1,1,1,1,1,7.463925,0.0445,0.013146
3,Arcticgroundsquirrel,0.920,5.7,NaN,NaN,16.5,NaN,25.0,5,2,3,1,1,2.028600,0.0057,0.006196
4,Asianelephant,2547.000,4603.0,2.1,1.8,3.9,69.0,624.0,3,5,4,1,1,5616.135000,4.6030,0.001807

In [40]:
# sort values to see results.
animals.sort_values(by='ratio_brain_body', ascending=False)

,species,bodywt,brainwt,nondreaming,dreaming,totalsleep,lifespan,gestation,predation,exposure,danger,nova_coluna,nome_coluna,bodywt_pounds,brainwt_kg,ratio_brain_body
26,Groundsquirrel,0.101,4.00,10.4,3.4,13.8,9.0,28.0,5,1,3,1,1,0.222705,0.00400,0.039604
41,Owlmonkey,0.480,15.50,15.2,1.8,17.0,12.0,140.0,2,2,2,1,1,1.058400,0.01550,0.032292
31,Lessershort-tailedshrew,0.005,0.14,7.7,1.4,9.1,2.6,21.5,5,2,4,1,1,0.011025,0.00014,0.028000
49,Rhesusmonkey,6.800,179.00,8.4,1.2,9.6,29.0,164.0,2,3,2,1,1,14.994000,0.17900,0.026324
32,Littlebrownbat,0.010,0.25,17.9,2.0,19.9,24.0,50.0,1,1,1,1,1,0.022050,0.00025,0.025000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,Wateropossum,3.500,3.90,12.8,6.6,19.4,3.0,14.0,2,1,1,1,1,7.717500,0.00390,0.001114
7,Braziliantapir,160.000,169.00,5.2,1.0,6.2,30.4,392.0,4,5,4,1,1,352.800000,0.16900,0.001056
44,Pig,192.000,180.00,6.5,1.9,8.4,27.0,115.0,4,4,4,1,1,423.360000,0.18000,0.000937
11,Cow,465.000,423.00,3.2,0.7,3.9,30.0,281.0,5,5,5,1,1,1025.325000,0.42300,0.000910
0,Africanelephant,6654.000,5712.00,NaN,NaN,3.3,38.6,645.0,3,5,3,1,1,14672.070000,5.71200,0.000858

## Performing calculations row-wise

### Calculate the sum of weights for each animal

In [43]:
animals[['bodywt','brainwt_kg']].sum(axis=1)

0     6659.7120
1        1.0066
2        3.4295
3        0.9257
4     2551.6030
        ...
57       2.0123
58       0.1065
59       4.2480
60       3.5039
61       4.0670
Length: 62, dtype: float64

In [44]:
animals['totalwt'] = animals[['bodywt','brainwt_kg']].sum(axis=1)

In [45]:
animals['totalwt'] = animals['bodywt'] + animals['brainwt_kg']

In [46]:
animals

,species,bodywt,brainwt,nondreaming,dreaming,totalsleep,lifespan,gestation,predation,exposure,danger,nova_coluna,nome_coluna,bodywt_pounds,brainwt_kg,ratio_brain_body,totalwt
0,Africanelephant,6654.000,5712.0,NaN,NaN,3.3,38.6,645.0,3,5,3,1,1,14672.070000,5.7120,0.000858,6659.7120
1,Africangiantpouchedrat,1.000,6.6,6.3,2.0,8.3,4.5,42.0,3,1,3,1,1,2.205000,0.0066,0.006600,1.0066
2,ArcticFox,3.385,44.5,NaN,NaN,12.5,14.0,60.0,1,1,1,1,1,7.463925,0.0445,0.013146,3.4295
3,Arcticgroundsquirrel,0.920,5.7,NaN,NaN,16.5,NaN,25.0,5,2,3,1,1,2.028600,0.0057,0.006196,0.9257
4,Asianelephant,2547.000,4603.0,2.1,1.8,3.9,69.0,624.0,3,5,4,1,1,5616.135000,4.6030,0.001807,2551.6030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,Treehyrax,2.000,12.3,4.9,0.5,5.4,7.5,200.0,3,1,3,1,1,4.410000,0.0123,0.006150,2.0123
58,Treeshrew,0.104,2.5,13.2,2.6,15.8,2.3,46.0,3,2,2,1,1,0.229320,0.0025,0.024038,0.1065
59,Vervet,4.190,58.0,9.7,0.6,10.3,24.0,210.0,4,3,4,1,1,9.238950,0.0580,0.013842,4.2480
60,Wateropossum,3.500,3.9,12.8,6.6,19.4,3.0,14.0,2,1,1,1,1,7.717500,0.0039,0.001114,3.5039
61,Yellow-belliedmarmot,4.050,17.0,NaN,NaN,NaN,13.0,38.0,3,1,1,1,1,8.930250,0.0170,0.004198,4.0670

In [50]:
y = animals.sample(10).loc[:, :'totalsleep']

In [51]:
y

                species  bodywt  brainwt  nondreaming  dreaming  totalsleep
38     NAmericanopossum   1.700     6.30         13.8       5.6        19.4
5                Baboon  10.550   179.50          9.1       0.7         9.8
52              Roedeer  14.830    98.20          NaN       NaN         2.6
49         Rhesusmonkey   6.800   179.00          8.4       1.2         9.6
32       Littlebrownbat   0.010     0.25         17.9       2.0        19.9
48               Redfox   4.235    50.40          7.4       2.4         9.8
54            Slowloris   1.400    12.50          NaN       NaN        11.0
14  EasternAmericanmole   0.075     1.20          6.3       2.1         8.4
37            Muskshrew   0.048     0.33         10.8       2.0        12.8
12       Deserthedgehog   0.550     2.40          7.6       2.7        10.3

In [52]:
y['bodywt']

38     1.700
5     10.550
52    14.830
49     6.800
32     0.010
48     4.235
54     1.400
14     0.075
37     0.048
12     0.550
Name: bodywt, dtype: float64

In [53]:
animals['bodywt']

0     6654.000
1        1.000
2        3.385
3        0.920
4     2547.000
        ...
57       2.000
58       0.104
59       4.190
60       3.500
61       4.050
Name: bodywt, Length: 62, dtype: float64

In [56]:
(y['bodywt'] + animals['bodywt']).isna().mean()

0.8387096774193549

In [58]:
(y['bodywt'] + animals['bodywt']).head(10)

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
5    21.1
6     NaN
7     NaN
8     NaN
9     NaN
Name: bodywt, dtype: float64

In [71]:
animals

,species,bodywt,brainwt,nondreaming,dreaming,totalsleep,lifespan,gestation,predation,exposure,danger,nova_coluna,nome_coluna,bodywt_pounds,brainwt_kg,ratio_brain_body,totalwt
0,Africanelephant,6654.000,5712.0,NaN,NaN,3.3,38.6,645.0,3,5,3,1,1,14672.070000,5.7120,0.000858,6659.7120
1,Africangiantpouchedrat,1.000,6.6,6.3,2.0,8.3,4.5,42.0,3,1,3,1,1,2.205000,0.0066,0.006600,1.0066
2,ArcticFox,3.385,44.5,NaN,NaN,12.5,14.0,60.0,1,1,1,1,1,7.463925,0.0445,0.013146,3.4295
3,Arcticgroundsquirrel,0.920,5.7,NaN,NaN,16.5,NaN,25.0,5,2,3,1,1,2.028600,0.0057,0.006196,0.9257
4,Asianelephant,2547.000,4603.0,2.1,1.8,3.9,69.0,624.0,3,5,4,1,1,5616.135000,4.6030,0.001807,2551.6030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,Treehyrax,2.000,12.3,4.9,0.5,5.4,7.5,200.0,3,1,3,1,1,4.410000,0.0123,0.006150,2.0123
58,Treeshrew,0.104,2.5,13.2,2.6,15.8,2.3,46.0,3,2,2,1,1,0.229320,0.0025,0.024038,0.1065
59,Vervet,4.190,58.0,9.7,0.6,10.3,24.0,210.0,4,3,4,1,1,9.238950,0.0580,0.013842,4.2480
60,Wateropossum,3.500,3.9,12.8,6.6,19.4,3.0,14.0,2,1,1,1,1,7.717500,0.0039,0.001114,3.5039
61,Yellow-belliedmarmot,4.050,17.0,NaN,NaN,NaN,13.0,38.0,3,1,1,1,1,8.930250,0.0170,0.004198,4.0670

In [81]:
animals.loc[animals['predation'] > animals['exposure'], 'poder'] = 'fraco'
animals.loc[(animals['predation'] < animals['exposure']), 'poder'] = 'forte'
animals.loc[(animals['predation'] == animals['exposure']), 'poder'] = 'nada'

In [82]:
animals['poder'].value_counts()

nada     29
fraco    24
forte     9
Name: poder, dtype: int64

In [84]:
animals.groupby(by='poder').mean()

,bodywt,brainwt,nondreaming,dreaming,totalsleep,lifespan,gestation,predation,exposure,danger,nova_coluna,nome_coluna,bodywt_pounds,brainwt_kg,ratio_brain_body,totalwt
poder,,,,,,,,,,,,,,,,
forte,1077.723333,1277.011111,6.016667,1.733333,7.725000,36.177778,310.375000,2.111111,3.777778,2.333333,1.0,1.0,2376.379950,1.277011,0.006400,1079.000344
fraco,1.300333,8.011250,9.813636,2.368182,12.369565,6.640000,63.613636,3.250000,1.458333,2.500000,1.0,1.0,2.867235,0.008011,0.010985,1.308345
nada,89.457276,202.377586,8.215000,1.640909,9.800000,23.948276,156.214286,2.793103,2.793103,2.793103,1.0,1.0,197.253293,0.202378,0.009498,89.659653

# Conditional Calculations

In [67]:
animals.head(2)

,species,bodywt,brainwt,nondreaming,dreaming,totalsleep,lifespan,gestation,predation,exposure,danger,nova_coluna,nome_coluna,bodywt_pounds,brainwt_kg,ratio_brain_body,totalwt
0,Africanelephant,6654.0,5712.0,NaN,NaN,3.3,38.6,645.0,3,5,3,1,1,14672.070,5.7120,0.000858,6659.7120
1,Africangiantpouchedrat,1.0,6.6,6.3,2.0,8.3,4.5,42.0,3,1,3,1,1,2.205,0.0066,0.006600,1.0066

In [70]:
mask = animals.duplicated(subset=['predation','exposure','danger'], keep=False)

animals.loc[mask, :]

,species,bodywt,brainwt,nondreaming,dreaming,totalsleep,lifespan,gestation,predation,exposure,danger,nova_coluna,nome_coluna,bodywt_pounds,brainwt_kg,ratio_brain_body,totalwt
1,Africangiantpouchedrat,1.000,6.60,6.3,2.0,8.3,4.5,42.0,3,1,3,1,1,2.205000,0.00660,0.006600,1.00660
2,ArcticFox,3.385,44.50,NaN,NaN,12.5,14.0,60.0,1,1,1,1,1,7.463925,0.04450,0.013146,3.42950
4,Asianelephant,2547.000,4603.00,2.1,1.8,3.9,69.0,624.0,3,5,4,1,1,5616.135000,4.60300,0.001807,2551.60300
5,Baboon,10.550,179.50,9.1,0.7,9.8,27.0,180.0,4,4,4,1,1,23.262750,0.17950,0.017014,10.72950
6,Bigbrownbat,0.023,0.30,15.8,3.9,19.7,19.0,35.0,1,1,1,1,1,0.050715,0.00030,0.013043,0.02330
8,Cat,3.300,25.60,10.9,3.6,14.5,28.0,63.0,1,2,1,1,1,7.276500,0.02560,0.007758,3.32560
9,Chimpanzee,52.160,440.00,8.3,1.4,9.7,50.0,230.0,1,1,1,1,1,115.012800,0.44000,0.008436,52.60000
11,Cow,465.000,423.00,3.2,0.7,3.9,30.0,281.0,5,5,5,1,1,1025.325000,0.42300,0.000910,465.42300
12,Deserthedgehog,0.550,2.40,7.6,2.7,10.3,NaN,NaN,2,1,2,1,1,1.212750,0.00240,0.004364,0.55240
13,Donkey,187.100,419.00,NaN,NaN,3.1,40.0,365.0,5,5,5,1,1,412.555500,0.41900,0.002239,187.51900
14,EasternAmericanmole,0.075,1.20,6.3,2.1,8.4,3.5,42.0,1,1,1,1,1,0.165375,0.00120,0.016000,0.07620
15,Echidna,3.000,25.00,8.6,0.0,8.6,50.0,28.0,2,2,2,1,1,6.615000,0.02500,0.008333,3.02500
16,Europeanhedgehog,0.785,3.50,6.6,4.1,10.7,6.0,42.0,2,2,2,1,1,1.730925,0.00350,0.004459,0.78850
17,Galago,0.200,5.00,9.5,1.2,10.7,10.4,120.0,2,2,2,1,1,0.441000,0.00500,0.025000,0.20500
18,Genet,1.410,17.50,4.8,1.3,6.1,34.0,NaN,1,2,1,1,1,3.109050,0.01750,0.012411,1.42750
19,Giantarmadillo,60.000,81.00,12.0,6.1,18.1,7.0,NaN,1,1,1,1,1,132.300000,0.08100,0.001350,60.08100
20,Giraffe,529.000,680.00,NaN,0.3,NaN,28.0,400.0,5,5,5,1,1,1166.445000,0.68000,0.001285,529.68000
21,Goat,27.660,115.00,3.3,0.5,3.8,20.0,148.0,5,5,5,1,1,60.990300,0.11500,0.004158,27.77500
22,Goldenhamster,0.120,1.00,11.0,3.4,14.4,3.9,16.0,3,1,2,1,1,0.264600,0.00100,0.008333,0.12100
25,Graywolf,36.330,119.50,NaN,NaN,13.0,16.2,63.0,1,1,1,1,1,80.107650,0.11950,0.003289,36.44950
28,Horse,521.000,655.00,2.1,0.8,2.9,46.0,336.0,5,5,5,1,1,1148.805000,0.65500,0.001257,521.65500
29,Jaguar,100.000,157.00,NaN,NaN,10.8,22.4,100.0,1,1,1,1,1,220.500000,0.15700,0.001570,100.15700
30,Kangaroo,35.000,56.00,NaN,NaN,NaN,16.3,33.0,3,5,4,1,1,77.175000,0.05600,0.001600,35.05600
32,Littlebrownbat,0.010,0.25,17.9,2.0,19.9,24.0,50.0,1,1,1,1,1,0.022050,0.00025,0.025000,0.01025
33,Man,62.000,1320.00,6.1,1.9,8.0,100.0,267.0,1,1,1,1,1,136.710000,1.32000,0.021290,63.32000
34,Molerat,0.122,3.00,8.2,2.4,10.6,NaN,30.0,2,1,1,1,1,0.269010,0.00300,0.024590,0.12500
35,Mountainbeaver,1.350,8.10,8.4,2.8,11.2,NaN,45.0,3,1,3,1,1,2.976750,0.00810,0.006000,1.35810
36,Mouse,0.023,0.40,11.9,1.3,13.2,3.2,19.0,4,1,3,1,1,0.050715,0.00040,0.017391,0.02340
37,Muskshrew,0.048,0.33,10.8,2.0,12.8,2.0,30.0,4,1,3,1,1,0.105840,0.00033,0.006875,0.04833
38,NAmericanopossum,1.700,6.30,13.8,5.6,19.4,5.0,12.0,2,1,1,1,1,3.748500,0.00630,0.003706,1.70630
39,Nine-bandedarmadillo,3.500,10.80,14.3,3.1,17.4,6.5,120.0,2,1,1,1,1,7.717500,0.01080,0.003086,3.51080
40,Okapi,250.000,490.00,NaN,1.0,NaN,23.6,440.0,5,5,5,1,1,551.250000,0.49000,0.001960,250.49000
41,Owlmonkey,0.480,15.50,15.2,1.8,17.0,12.0,140.0,2,2,2,1,1,1.058400,0.01550,0.032292,0.49550
42,Patasmonkey,10.000,115.00,10.0,0.9,10.9,20.2,170.0,4,4,4,1,1,22.050000,0.11500,0.011500,10.11500
43,Phanlanger,1.620,11.40,11.9,1.8,13.7,13.0,17.0,2,1,2,1,1,3.572100,0.01140,0.007037,1.63140
44,Pig,192.000,180.00,6.5,1.9,8.4,27.0,115.0,4,4,4,1,1,423.360000,0.18000,0.000937,192.18000
45,Rabbit,2.500,12.10,7.5,0.9,8.4,18.0,31.0,5,5,5,1,1,5.512500,0.01210,0.004840,2.51210
46,Raccoon,4.288,39.20,NaN,NaN,12.5,13.7,63.0,2,2,2,1,1,9.455040,0.03920,0.009142,4.32720
47,Rat,0.280,1.90,10.6,2.6,13.2,4.7,21.0,3,1,3,1,1,0.617400,0.00190,0.006786,0.28190
48,Redfox,4.235,50.40,7.4,2.4,9.8,9.8,52.0,1,1,1,1,1,9.338175,0.05040,0.011901,4.28540
50,Rockhyrax(Heterob),0.750,12.30,5.7,0.9,6.6,7.0,225.0,2,2,2,1,1,1.653750,0.01230,0.016400,0.76230
52,Roedeer,14.830,98.20,NaN,NaN,2.6,17.0,150.0,5,5,5,1,1,32.700150,0.09820,0.006622,14.92820
53,Sheep,55.500,175.00,3.2,0.6,3.8,20.0,151.0,5,5,5,1,1,122.377500,0.17500,0.003153,55.67500
54,Slowloris,1.400,12.50,NaN,NaN,11.0,12.7,90.0,2,2,2,1,1,3.087000,0.01250,0.008929,1.41250
55,Starnosedmole,0.060,1.00,8.1,2.2,10.3,3.5,NaN,3,1,2,1,1,0.132300,0.00100,0.016667,0.06100
56,Tenrec,0.900,2.60,11.0,2.3,13.3,4.5,60.0,2,1,2,1,1,1.984500,0.00260,0.002889,0.90260
57,Treehyrax,2.000,12.30,4.9,0.5,5.4,7.5,200.0,3,1,3,1,1,4.410000,0.01230,0.006150,2.01230
60,Wateropossum,3.500,3.90,12.8,6.6,19.4,3.0,14.0,2,1,1,1,1,7.717500,0.00390,0.001114,3.50390

## Assign values based on conditions

In [88]:
# normalize = True returns percentages.
animals.poder.value_counts(normalize=True)

nada     0.467742
fraco    0.387097
forte    0.145161
Name: poder, dtype: float64

In [89]:
(animals['danger'] >= 4)

0     False
1     False
2     False
3     False
4      True
      ...
57    False
58    False
59     True
60    False
61    False
Name: danger, Length: 62, dtype: bool

In [91]:
animals.loc[(animals['danger'] >= 4), 'flag_extincao'] = 1

In [92]:
# animals.loc[(animals['danger'] < 4), 'flag_extincao'] = 1
animals.loc[~(animals['danger'] >= 4), 'flag_extincao'] = 0

In [93]:
animals

,species,bodywt,brainwt,nondreaming,dreaming,totalsleep,lifespan,gestation,predation,exposure,danger,nova_coluna,nome_coluna,bodywt_pounds,brainwt_kg,ratio_brain_body,totalwt,extincao,poder,flag_extincao
0,Africanelephant,6654.000,5712.0,NaN,NaN,3.3,38.6,645.0,3,5,3,1,1,14672.070000,5.7120,0.000858,6659.7120,forte,forte,0.0
1,Africangiantpouchedrat,1.000,6.6,6.3,2.0,8.3,4.5,42.0,3,1,3,1,1,2.205000,0.0066,0.006600,1.0066,fraco,fraco,0.0
2,ArcticFox,3.385,44.5,NaN,NaN,12.5,14.0,60.0,1,1,1,1,1,7.463925,0.0445,0.013146,3.4295,nada,nada,0.0
3,Arcticgroundsquirrel,0.920,5.7,NaN,NaN,16.5,NaN,25.0,5,2,3,1,1,2.028600,0.0057,0.006196,0.9257,fraco,fraco,0.0
4,Asianelephant,2547.000,4603.0,2.1,1.8,3.9,69.0,624.0,3,5,4,1,1,5616.135000,4.6030,0.001807,2551.6030,forte,forte,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,Treehyrax,2.000,12.3,4.9,0.5,5.4,7.5,200.0,3,1,3,1,1,4.410000,0.0123,0.006150,2.0123,fraco,fraco,0.0
58,Treeshrew,0.104,2.5,13.2,2.6,15.8,2.3,46.0,3,2,2,1,1,0.229320,0.0025,0.024038,0.1065,fraco,fraco,0.0
59,Vervet,4.190,58.0,9.7,0.6,10.3,24.0,210.0,4,3,4,1,1,9.238950,0.0580,0.013842,4.2480,fraco,fraco,1.0
60,Wateropossum,3.500,3.9,12.8,6.6,19.4,3.0,14.0,2,1,1,1,1,7.717500,0.0039,0.001114,3.5039,fraco,fraco,0.0
61,Yellow-belliedmarmot,4.050,17.0,NaN,NaN,NaN,13.0,38.0,3,1,1,1,1,8.930250,0.0170,0.004198,4.0670,fraco,fraco,0.0

In [98]:
animals.groupby(by='flag_extincao').agg(['mean','median']).T

flag_extincao                   0.0         1.0
bodywt           mean    170.050674  263.831579
                 median    1.410000   35.000000
brainwt          mean    211.964651  444.202105
                 median   11.400000  169.000000
nondreaming      mean      9.655882    6.285714
                 median    9.050000    6.950000
dreaming         mean      2.447059    0.962500
                 median    2.150000    0.850000
totalsleep       mean     11.978571    6.737500
                 median   11.600000    7.200000
lifespan         mean     17.415385   24.931579
                 median   10.400000   23.600000
gestation        mean    103.307692  222.500000
                 median   52.000000  170.000000
predation        mean      2.139535    4.526316
                 median    2.000000    5.000000
exposure         mean      1.534884    4.421053
                 median    1.000000    5.000000
danger           mean      1.790698    4.473684
                 median    2.000000    4.000000
nova_coluna      mean      1.000000    1.000000
                 median    1.000000    1.000000
nome_coluna      mean      1.000000    1.000000
                 median    1.000000    1.000000
bodywt_pounds    mean    374.961737  581.748632
                 median    3.109050   77.175000
brainwt_kg       mean      0.211965    0.444202
                 median    0.011400    0.169000
ratio_brain_body mean      0.011027    0.006449
                 median    0.007758    0.003153
totalwt          mean    170.262639  264.275781
                 median    1.427500   35.056000

In [101]:
avg_bodywt = animals['bodywt'].mean()
avg_bodywt

198.78998387096775

In [109]:
print(f'😅')

😅

In [102]:
animals.loc[(animals.bodywt > avg_bodywt), 'flag_overweight'] = True
animals.loc[~(animals.bodywt > avg_bodywt), 'flag_overweight'] = False

In [106]:
animals.groupby(by='flag_overweight').mean().T

flag_overweight        False        True
bodywt             20.945073  1596.142857
brainwt            83.369455  1852.714286
nondreaming         9.086667     2.466667
dreaming            2.088889     0.920000
totalsleep         11.035849     5.200000
lifespan           17.223529    39.214286
gestation         103.500000   425.428571
predation           2.745455     3.857143
exposure            2.109091     4.857143
danger              2.436364     4.000000
nova_coluna         1.000000     1.000000
nome_coluna         1.000000     1.000000
bodywt_pounds      46.183885  3519.495000
brainwt_kg          0.083369     1.852714
ratio_brain_body    0.010667     0.001434
totalwt            21.028442  1597.995571
flag_extincao       0.254545     0.714286

In [111]:
animals['emoji'] = '😅'

In [113]:
animals

,species,bodywt,brainwt,nondreaming,dreaming,totalsleep,lifespan,gestation,predation,exposure,...,nome_coluna,bodywt_pounds,brainwt_kg,ratio_brain_body,totalwt,extincao,poder,flag_extincao,flag_overweight,emoji
0,Africanelephant,6654.000,5712.0,NaN,NaN,3.3,38.6,645.0,3,5,...,1,14672.070000,5.7120,0.000858,6659.7120,forte,forte,0.0,True,😅
1,Africangiantpouchedrat,1.000,6.6,6.3,2.0,8.3,4.5,42.0,3,1,...,1,2.205000,0.0066,0.006600,1.0066,fraco,fraco,0.0,False,😅
2,ArcticFox,3.385,44.5,NaN,NaN,12.5,14.0,60.0,1,1,...,1,7.463925,0.0445,0.013146,3.4295,nada,nada,0.0,False,😅
3,Arcticgroundsquirrel,0.920,5.7,NaN,NaN,16.5,NaN,25.0,5,2,...,1,2.028600,0.0057,0.006196,0.9257,fraco,fraco,0.0,False,😅
4,Asianelephant,2547.000,4603.0,2.1,1.8,3.9,69.0,624.0,3,5,...,1,5616.135000,4.6030,0.001807,2551.6030,forte,forte,1.0,True,😅
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,Treehyrax,2.000,12.3,4.9,0.5,5.4,7.5,200.0,3,1,...,1,4.410000,0.0123,0.006150,2.0123,fraco,fraco,0.0,False,😅
58,Treeshrew,0.104,2.5,13.2,2.6,15.8,2.3,46.0,3,2,...,1,0.229320,0.0025,0.024038,0.1065,fraco,fraco,0.0,False,😅
59,Vervet,4.190,58.0,9.7,0.6,10.3,24.0,210.0,4,3,...,1,9.238950,0.0580,0.013842,4.2480,fraco,fraco,1.0,False,😅
60,Wateropossum,3.500,3.9,12.8,6.6,19.4,3.0,14.0,2,1,...,1,7.717500,0.0039,0.001114,3.5039,fraco,fraco,0.0,False,😅
61,Yellow-belliedmarmot,4.050,17.0,NaN,NaN,NaN,13.0,38.0,3,1,...,1,8.930250,0.0170,0.004198,4.0670,fraco,fraco,0.0,False,😅

### Quantiles
*Touching statistics*

![Data](images/data_quantiles.png)

![Percentiles](images/data_quantiles_q10.png)

![Quartiles](images/quartiles.jpg)

> Percentiles: 
    - q50 means that 50% of your dataset is below that number. That is the median value.
    - q90 means that 90% of your dataset is below that number.
    - q10 means that 10% of your dataset is below that number.

> Calculating the q50

In [115]:
animals['bodywt'].median()

3.3425

In [127]:
animals = animals.drop([3,4])

In [128]:
q90 = animals['bodywt'].quantile(0.9)

In [129]:
q90

193.50000000000003

In [130]:
(animals['bodywt'] < q90).mean()

0.9

In [131]:
animals.shape

(60, 22)

In [132]:
np.quantile(animals['bodywt'], q=0.9)

193.50000000000003

In [134]:
animals['bodywt'].quantile(np.arange(0,1.1, 0.1))

0.0       0.0050
0.1       0.0735
0.2       0.2640
0.3       0.8655
0.4       1.5360
0.5       3.3425
0.6       4.2080
0.7      18.6790
0.8      60.4000
0.9     193.5000
1.0    6654.0000
Name: bodywt, dtype: float64

In [140]:
animals = animals.drop(5)

In [143]:
pd.qcut(animals['bodywt'], q=2, labels=['LEVE', 'SOBREPESO']).value_counts()

LEVE         30
SOBREPESO    29
Name: bodywt, dtype: int64

> Calculating the threshold for different quantiles

In [144]:
# say that animals above quantile 0.95 (percentile 95%) are super-overweight
animals.bodywt.quantile(0.95)

470.5999999999997

In [145]:
q95 = animals.bodywt.quantile(0.95)

In [146]:
# say that animals below quantile 0.1 (percentile 10%) are super-skinny
q10 = animals.bodywt.quantile(0.1)

In [147]:
q10

0.07200000000000001

In [148]:
pd.qcut(animals.drop(labels=[1,2]).bodywt, 10, labels=['a','b','c','d','e','f','g','h','i','j'])

0     j
6     a
7     i
8     e
9     h
10    c
11    j
12    c
13    i
14    b
15    e
16    d
17    b
18    d
19    h
20    j
21    g
22    b
23    j
24    i
25    h
26    b
27    d
28    j
29    i
30    h
31    a
32    a
33    i
34    b
35    d
36    a
37    a
38    e
39    f
40    j
41    c
42    g
43    e
44    i
45    e
46    g
47    c
48    g
49    g
50    c
51    f
52    g
53    h
54    d
55    a
56    d
57    e
58    b
59    f
60    f
61    f
Name: bodywt, dtype: category
Categories (10, object): [a < b < c < d ... g < h < i < j]

In [149]:
# Categorizing
pd.qcut(animals.drop(labels=[1,2]).bodywt, 10, labels=['a','b','c','d','e','f','g','h','i','j']).value_counts()

j    6
i    6
g    6
e    6
d    6
b    6
a    6
h    5
f    5
c    5
Name: bodywt, dtype: int64

In [150]:
q10

0.07200000000000001

> Selecting (and counting) the observations that are above (or below) that threshold

In [250]:
animals.query(f'bodywt < {q10}')

,species,bodywt,brainwt,nondreaming,dreaming,totalsleep,lifespan,gestation,predation,exposure,danger,coluna_com_espaco,colunah_com_acenntuuuh,nome_coluna,bodywt_pounds,brainwt_kg,ratio_brain_body,totalwt,flag_extincao,flag_overweight
6,Bigbrownbat,0.023,0.30,15.8,3.9,19.7,19.0,35.0,1,1,1,-1,-100000,1,0.050715,0.00030,0.013043,0.02330,0.0,False
14,EasternAmericanmole,0.075,1.20,6.3,2.1,8.4,3.5,42.0,1,1,1,-1,-100000,1,0.165375,0.00120,0.016000,0.07620,0.0,False
31,Lessershort-tailedshrew,0.005,0.14,7.7,1.4,9.1,2.6,21.5,5,2,4,-1,-100000,1,0.011025,0.00014,0.028000,0.00514,1.0,False
32,Littlebrownbat,0.010,0.25,17.9,2.0,19.9,24.0,50.0,1,1,1,-1,-100000,1,0.022050,0.00025,0.025000,0.01025,0.0,False
36,Mouse,0.023,0.40,11.9,1.3,13.2,3.2,19.0,4,1,3,-1,-100000,1,0.050715,0.00040,0.017391,0.02340,0.0,False
37,Muskshrew,0.048,0.33,10.8,2.0,12.8,2.0,30.0,4,1,3,-1,-100000,1,0.105840,0.00033,0.006875,0.04833,0.0,False
55,Starnosedmole,0.060,1.00,8.1,2.2,10.3,3.5,NaN,3,1,2,-1,-100000,1,0.132300,0.00100,0.016667,0.06100,0.0,False

In [152]:
# selecting them:

animals.loc[(animals.bodywt < q10), 'flag_extinction'] = 10

In [153]:
# inputing value based on a condition.
animals.loc[(animals.bodywt < q10),:]

,species,bodywt,brainwt,nondreaming,dreaming,totalsleep,lifespan,gestation,predation,exposure,...,bodywt_pounds,brainwt_kg,ratio_brain_body,totalwt,extincao,poder,flag_extincao,flag_overweight,emoji,flag_extinction
6,Bigbrownbat,0.023,0.30,15.8,3.9,19.7,19.0,35.0,1,1,...,0.050715,0.00030,0.013043,0.02330,nada,nada,0.0,False,😅,10.0
31,Lessershort-tailedshrew,0.005,0.14,7.7,1.4,9.1,2.6,21.5,5,2,...,0.011025,0.00014,0.028000,0.00514,fraco,fraco,1.0,False,😅,10.0
32,Littlebrownbat,0.010,0.25,17.9,2.0,19.9,24.0,50.0,1,1,...,0.022050,0.00025,0.025000,0.01025,nada,nada,0.0,False,😅,10.0
36,Mouse,0.023,0.40,11.9,1.3,13.2,3.2,19.0,4,1,...,0.050715,0.00040,0.017391,0.02340,fraco,fraco,0.0,False,😅,10.0
37,Muskshrew,0.048,0.33,10.8,2.0,12.8,2.0,30.0,4,1,...,0.105840,0.00033,0.006875,0.04833,fraco,fraco,0.0,False,😅,10.0
55,Starnosedmole,0.060,1.00,8.1,2.2,10.3,3.5,NaN,3,1,...,0.132300,0.00100,0.016667,0.06100,fraco,fraco,0.0,False,😅,10.0

## Numpy where

In [154]:
q95 = animals.bodywt.quantile(0.95)

In [155]:
import numpy as np

> np.where(condition is true, then this value, else this value)

In [156]:
q95

470.5999999999997

In [157]:
np.where(animals['bodywt'] > q95, 'SUPER-OVERWEIGHT','NORMAL')

array(['SUPER-OVERWEIGHT', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL',
       'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL',
       'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL',
       'SUPER-OVERWEIGHT', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL',
       'NORMAL', 'NORMAL', 'NORMAL', 'SUPER-OVERWEIGHT', 'NORMAL',
       'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL',
       'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL',
       'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL',
       'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL',
       'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL',
       'NORMAL', 'NORMAL'], dtype='<U16')

In [158]:
animals['class'] = np.where(animals['bodywt'] > q95, 'SUPER-OVERWEIGHT','NORMAL')

In [159]:
animals

,species,bodywt,brainwt,nondreaming,dreaming,totalsleep,lifespan,gestation,predation,exposure,...,brainwt_kg,ratio_brain_body,totalwt,extincao,poder,flag_extincao,flag_overweight,emoji,flag_extinction,class
0,Africanelephant,6654.000,5712.00,NaN,NaN,3.3,38.6,645.0,3,5,...,5.71200,0.000858,6659.71200,forte,forte,0.0,True,😅,NaN,SUPER-OVERWEIGHT
1,Africangiantpouchedrat,1.000,6.60,6.3,2.0,8.3,4.5,42.0,3,1,...,0.00660,0.006600,1.00660,fraco,fraco,0.0,False,😅,NaN,NORMAL
2,ArcticFox,3.385,44.50,NaN,NaN,12.5,14.0,60.0,1,1,...,0.04450,0.013146,3.42950,nada,nada,0.0,False,😅,NaN,NORMAL
6,Bigbrownbat,0.023,0.30,15.8,3.9,19.7,19.0,35.0,1,1,...,0.00030,0.013043,0.02330,nada,nada,0.0,False,😅,10.0,NORMAL
7,Braziliantapir,160.000,169.00,5.2,1.0,6.2,30.4,392.0,4,5,...,0.16900,0.001056,160.16900,forte,forte,1.0,False,😅,NaN,NORMAL
8,Cat,3.300,25.60,10.9,3.6,14.5,28.0,63.0,1,2,...,0.02560,0.007758,3.32560,forte,forte,0.0,False,😅,NaN,NORMAL
9,Chimpanzee,52.160,440.00,8.3,1.4,9.7,50.0,230.0,1,1,...,0.44000,0.008436,52.60000,nada,nada,0.0,False,😅,NaN,NORMAL
10,Chinchilla,0.425,6.40,11.0,1.5,12.5,7.0,112.0,5,4,...,0.00640,0.015059,0.43140,fraco,fraco,1.0,False,😅,NaN,NORMAL
11,Cow,465.000,423.00,3.2,0.7,3.9,30.0,281.0,5,5,...,0.42300,0.000910,465.42300,nada,nada,1.0,True,😅,NaN,NORMAL
12,Deserthedgehog,0.550,2.40,7.6,2.7,10.3,NaN,NaN,2,1,...,0.00240,0.004364,0.55240,fraco,fraco,0.0,False,😅,NaN,NORMAL
13,Donkey,187.100,419.00,NaN,NaN,3.1,40.0,365.0,5,5,...,0.41900,0.002239,187.51900,nada,nada,1.0,False,😅,NaN,NORMAL
14,EasternAmericanmole,0.075,1.20,6.3,2.1,8.4,3.5,42.0,1,1,...,0.00120,0.016000,0.07620,nada,nada,0.0,False,😅,NaN,NORMAL
15,Echidna,3.000,25.00,8.6,0.0,8.6,50.0,28.0,2,2,...,0.02500,0.008333,3.02500,nada,nada,0.0,False,😅,NaN,NORMAL
16,Europeanhedgehog,0.785,3.50,6.6,4.1,10.7,6.0,42.0,2,2,...,0.00350,0.004459,0.78850,nada,nada,0.0,False,😅,NaN,NORMAL
17,Galago,0.200,5.00,9.5,1.2,10.7,10.4,120.0,2,2,...,0.00500,0.025000,0.20500,nada,nada,0.0,False,😅,NaN,NORMAL
18,Genet,1.410,17.50,4.8,1.3,6.1,34.0,NaN,1,2,...,0.01750,0.012411,1.42750,forte,forte,0.0,False,😅,NaN,NORMAL
19,Giantarmadillo,60.000,81.00,12.0,6.1,18.1,7.0,NaN,1,1,...,0.08100,0.001350,60.08100,nada,nada,0.0,False,😅,NaN,NORMAL
20,Giraffe,529.000,680.00,NaN,0.3,NaN,28.0,400.0,5,5,...,0.68000,0.001285,529.68000,nada,nada,1.0,True,😅,NaN,SUPER-OVERWEIGHT
21,Goat,27.660,115.00,3.3,0.5,3.8,20.0,148.0,5,5,...,0.11500,0.004158,27.77500,nada,nada,1.0,False,😅,NaN,NORMAL
22,Goldenhamster,0.120,1.00,11.0,3.4,14.4,3.9,16.0,3,1,...,0.00100,0.008333,0.12100,fraco,fraco,0.0,False,😅,NaN,NORMAL
23,Gorilla,207.000,406.00,NaN,NaN,12.0,39.3,252.0,1,4,...,0.40600,0.001961,207.40600,forte,forte,0.0,True,😅,NaN,NORMAL
24,Grayseal,85.000,325.00,4.7,1.5,6.2,41.0,310.0,1,3,...,0.32500,0.003824,85.32500,forte,forte,0.0,False,😅,NaN,NORMAL
25,Graywolf,36.330,119.50,NaN,NaN,13.0,16.2,63.0,1,1,...,0.11950,0.003289,36.44950,nada,nada,0.0,False,😅,NaN,NORMAL
26,Groundsquirrel,0.101,4.00,10.4,3.4,13.8,9.0,28.0,5,1,...,0.00400,0.039604,0.10500,fraco,fraco,0.0,False,😅,NaN,NORMAL
27,Guineapig,1.040,5.50,7.4,0.8,8.2,7.6,68.0,5,3,...,0.00550,0.005288,1.04550,fraco,fraco,1.0,False,😅,NaN,NORMAL
28,Horse,521.000,655.00,2.1,0.8,2.9,46.0,336.0,5,5,...,0.65500,0.001257,521.65500,nada,nada,1.0,True,😅,NaN,SUPER-OVERWEIGHT
29,Jaguar,100.000,157.00,NaN,NaN,10.8,22.4,100.0,1,1,...,0.15700,0.001570,100.15700,nada,nada,0.0,False,😅,NaN,NORMAL
30,Kangaroo,35.000,56.00,NaN,NaN,NaN,16.3,33.0,3,5,...,0.05600,0.001600,35.05600,forte,forte,1.0,False,😅,NaN,NORMAL
31,Lessershort-tailedshrew,0.005,0.14,7.7,1.4,9.1,2.6,21.5,5,2,...,0.00014,0.028000,0.00514,fraco,fraco,1.0,False,😅,10.0,NORMAL
32,Littlebrownbat,0.010,0.25,17.9,2.0,19.9,24.0,50.0,1,1,...,0.00025,0.025000,0.01025,nada,nada,0.0,False,😅,10.0,NORMAL
33,Man,62.000,1320.00,6.1,1.9,8.0,100.0,267.0,1,1,...,1.32000,0.021290,63.32000,nada,nada,0.0,False,😅,NaN,NORMAL
34,Molerat,0.122,3.00,8.2,2.4,10.6,NaN,30.0,2,1,...,0.00300,0.024590,0.12500,fraco,fraco,0.0,False,😅,NaN,NORMAL
35,Mountainbeaver,1.350,8.10,8.4,2.8,11.2,NaN,45.0,3,1,...,0.00810,0.006000,1.35810,fraco,fraco,0.0,False,😅,NaN,NORMAL
36,Mouse,0.023,0.40,11.9,1.3,13.2,3.2,19.0,4,1,...,0.00040,0.017391,0.02340,fraco,fraco,0.0,False,😅,10.0,NORMAL
37,Muskshrew,0.048,0.33,10.8,2.0,12.8,2.0,30.0,4,1,...,0.00033,0.006875,0.04833,fraco,fraco,0.0,False,😅,10.0,NORMAL
38,NAmericanopossum,1.700,6.30,13.8,5.6,19.4,5.0,12.0,2,1,...,0.00630,0.003706,1.70630,fraco,fraco,0.0,False,😅,NaN,NORMAL
39,Nine-bandedarmadillo,3.500,10.80,14.3,3.1,17.4,6.5,120.0,2,1,...,0.01080,0.003086,3.51080,fraco,fraco,0.0,False,😅,NaN,NORMAL
40,Okapi,250.000,490.00,NaN,1.0,NaN,23.6,440.0,5,5,...,0.49000,0.001960,250.49000,nada,nada,1.0,True,😅,NaN,NORMAL
41,Owlmonkey,0.480,15.50,15.2,1.8,17.0,12.0,140.0,2,2,...,0.01550,0.032292,0.49550,nada,nada,0.0,False,😅,NaN,NORMAL
42,Patasmonkey,10.000,115.00,10.0,0.9,10.9,20.2,170.0,4,4,...,0.11500,0.011500,10.11500,nada,nada,1.0,False,😅,NaN,NORMAL
43,Phanlanger,1.620,11.40,11.9,1.8,13.7,13.0,17.0,2,1,...,0.01140,0.007037,1.63140,fraco,fraco,0.0,False,😅,NaN,NORMAL
44,Pig,192.000,180.00,6.5,1.9,8.4,27.0,115.0,4,4,...,0.18000,0.000937,192.18000,nada,nada,1.0,False,😅,NaN,NORMAL
45,Rabbit,2.500,12.10,7.5,0.9,8.4,18.0,31.0,5,5,...,0.01210,0.004840,2.51210,nada,nada,1.0,False,😅,NaN,NORMAL
46,Raccoon,4.288,39.20,NaN,NaN,12.5,13.7,63.0,2,2,...,0.03920,0.009142,4.32720,nada,nada,0.0,False,😅,NaN,NORMAL
47,Rat,0.280,1.90,10.6,2.6,13.2,4.7,21.0,3,1,...,0.00190,0.006786,0.28190,fraco,fraco,0.0,False,😅,NaN,NORMAL
48,Redfox,4.235,50.40,7.4,2.4,9.8,9.8,52.0,1,1,...,0.05040,0.011901,4.28540,nada,nada,0.0,False,😅,NaN,NORMAL
49,Rhesusmonkey,6.800,179.00,8.4,1.2,9.6,29.0,164.0,2,3,...,0.17900,0.026324,6.97900,forte,forte,0.0,False,😅,NaN,NORMAL
50,Rockhyrax(Heterob),0.750,12.30,5.7,0.9,6.6,7.0,225.0,2,2,...,0.01230,0.016400,0.76230,nada,nada,0.0,False,😅,NaN,NORMAL
51,Rockhyrax(Procaviahab),3.600,21.00,4.9,0.5,5.4,6.0,225.0,3,2,...,0.02100,0.005833,3.62100,fraco,fraco,0.0,False,😅,NaN,NORMAL
52,Roedeer,14.830,98.20,NaN,NaN,2.6,17.0,150.0,5,5,...,0.09820,0.006622,14.92820,nada,nada,1.0,False,😅,NaN,NORMAL
53,Sheep,55.500,175.00,3.2,0.6,3.8,20.0,151.0,5,5,...,0.17500,0.003153,55.67500,nada,nada,1.0,False,😅,NaN,NORMAL
54,Slowloris,1.400,12.50,NaN,NaN,11.0,12.7,90.0,2,2,...,0.01250,0.008929,1.41250,nada,nada,0.0,False,😅,NaN,NORMAL
55,Starnosedmole,0.060,1.00,8.1,2.2,10.3,3.5,NaN,3,1,...,0.00100,0.016667,0.06100,fraco,fraco,0.0,False,😅,10.0,NORMAL
56,Tenrec,0.900,2.60,11.0,2.3,13.3,4.5,60.0,2,1,...,0.00260,0.002889,0.90260,fraco,fraco,0.0,False,😅,NaN,NORMAL
57,Treehyrax,2.000,12.30,4.9,0.5,5.4,7.5,200.0,3,1,...,0.01230,0.006150,2.01230,fraco,fraco,0.0,False,😅,NaN,NORMAL
58,Treeshrew,0.104,2.50,13.2,2.6,15.8,2.3,46.0,3,2,...,0.00250,0.024038,0.10650,fraco,fraco,0.0,False,😅,NaN,NORMAL
59,Vervet,4.190,58.00,9.7,0.6,10.3,24.0,210.0,4,3,...,0.05800,0.013842,4.24800,fraco,fraco,1.0,False,😅,NaN,NORMAL
60,Wateropossum,3.500,3.90,12.8,6.6,19.4,3.0,14.0,2,1,...,0.00390,0.001114,3.50390,fraco,fraco,0.0,False,😅,NaN,NORMAL
61,Yellow-belliedmarmot,4.050,17.00,NaN,NaN,NaN,13.0,38.0,3,1,...,0.01700,0.004198,4.06700,fraco,fraco,0.0,False,😅,NaN,NORMAL

In [166]:
q85 = animals['bodywt'].quantile(0.85)
q50 = animals['bodywt'].quantile(0.50)

In [167]:
animals['class'] = np.where(animals['bodywt'] > q95, 'SUPER-OVERWEIGHT',
                           np.where(animals['bodywt'] > q85, 'ALMOST-SUPER-OVERWEIGHT', 
                                   np.where(animals['bodywt'] > q50,'QUASI-ALMOST-SUPER-OVERWEIGHT','NORMAL')))

In [169]:
animals['wt_based_q95_q10'] = np.where(animals.bodywt > q95, 'SUPER-WEIGHT', 
                                       np.where(animals.bodywt < q10, 'SUPER-SKINNY', 'NORMAL'))

In [170]:
animals.wt_based_q95_q10.value_counts()

NORMAL          50
SUPER-SKINNY     6
SUPER-WEIGHT     3
Name: wt_based_q95_q10, dtype: int64

In [268]:
# animals.wt_based_q95.value_counts()

# Bonus: 

## Correlation

*Touching statistics*

In [171]:
animals.corr()

,bodywt,brainwt,nondreaming,dreaming,totalsleep,lifespan,gestation,predation,exposure,danger,nova_coluna,nome_coluna,bodywt_pounds,brainwt_kg,ratio_brain_body,totalwt,flag_extincao,flag_extinction
bodywt,1.000000,0.971657,-0.458742,-0.284926,-0.262746,0.208445,0.598037,0.067641,0.296606,0.103011,NaN,NaN,1.000000,0.971657,-0.180326,1.000000,-0.015610,NaN
brainwt,0.971657,1.000000,-0.379959,-0.248220,-0.308206,0.394022,0.674900,0.042157,0.313693,0.092932,NaN,NaN,0.971657,1.000000,-0.167932,0.971706,-0.001040,NaN
nondreaming,-0.458742,-0.379959,1.000000,0.533624,0.962597,-0.318933,-0.565557,-0.329140,-0.519695,-0.472897,NaN,NaN,-0.458742,-0.379959,0.321302,-0.459035,-0.400015,NaN
dreaming,-0.284926,-0.248220,0.533624,1.000000,0.742802,-0.308488,-0.523884,-0.439832,-0.540946,-0.574937,NaN,NaN,-0.284926,-0.248220,-0.048290,-0.285057,-0.479738,NaN
totalsleep,-0.262746,-0.308206,0.962597,0.742802,1.000000,-0.371849,-0.617458,-0.450838,-0.636022,-0.598231,NaN,NaN,-0.262746,-0.308206,0.258412,-0.262792,-0.494738,NaN
lifespan,0.208445,0.394022,-0.318933,-0.308488,-0.371849,1.000000,0.542304,-0.122013,0.308641,0.010710,NaN,NaN,0.208445,0.394022,-0.091057,0.208613,0.129133,NaN
gestation,0.598037,0.674900,-0.565557,-0.523884,-0.617458,0.542304,1.000000,0.243974,0.623262,0.368638,NaN,NaN,0.598037,0.674900,-0.295507,0.598120,0.332678,NaN
predation,0.067641,0.042157,-0.329140,-0.439832,-0.450838,-0.122013,0.243974,1.000000,0.642415,0.931259,NaN,NaN,0.067641,0.042157,-0.093892,0.067620,0.795228,NaN
exposure,0.296606,0.313693,-0.519695,-0.540946,-0.636022,0.308641,0.623262,0.642415,1.000000,0.782822,NaN,NaN,0.296606,0.313693,-0.342584,0.296628,0.827142,NaN
danger,0.103011,0.092932,-0.472897,-0.574937,-0.598231,0.010710,0.368638,0.931259,0.782822,1.000000,NaN,NaN,0.103011,0.092932,-0.220220,0.103005,0.869698,NaN
nova_coluna,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
nome_coluna,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bodywt_pounds,1.000000,0.971657,-0.458742,-0.284926,-0.262746,0.208445,0.598037,0.067641,0.296606,0.103011,NaN,NaN,1.000000,0.971657,-0.180326,1.000000,-0.015610,NaN
brainwt_kg,0.971657,1.000000,-0.379959,-0.248220,-0.308206,0.394022,0.674900,0.042157,0.313693,0.092932,NaN,NaN,0.971657,1.000000,-0.167932,0.971706,-0.001040,NaN
ratio_brain_body,-0.180326,-0.167932,0.321302,-0.048290,0.258412,-0.091057,-0.295507,-0.093892,-0.342584,-0.220220,NaN,NaN,-0.180326,-0.167932,1.000000,-0.180320,-0.255282,NaN
totalwt,1.000000,0.971706,-0.459035,-0.285057,-0.262792,0.208613,0.598120,0.067620,0.296628,0.103005,NaN,NaN,1.000000,0.971706,-0.180320,1.000000,-0.015598,NaN
flag_extincao,-0.015610,-0.001040,-0.400015,-0.479738,-0.494738,0.129133,0.332678,0.795228,0.827142,0.869698,NaN,NaN,-0.015610,-0.001040,-0.255282,-0.015598,1.000000,NaN
flag_extinction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Today:

- Creating columns based on: 
   - mathematical calculations, 
   - column based calculations, 
   - conditions
   - variable conditions
- quantiles 
- correlations