# Introduction to Pandas

Complete the following set of exercises to solidify your knowledge of Pandas fundamentals.

Please Check the "main" jupyter arquive!!!

# BONUS

#### 1 Create a random dataframe containing 3 columns and 10 rows. 

*Hint: You'll have to use a `numpy.random` method to create random observations*

In [6]:
import numpy as np
import pandas as pd

random_array = np.random.random((10,3))
print(random_array)

df = pd.DataFrame(random_array)
print(df)

[[0.93470251 0.83322532 0.34183148]
 [0.70249993 0.19841439 0.29087233]
 [0.72531664 0.45851413 0.49405856]
 [0.37073648 0.53829246 0.79484511]
 [0.0043749  0.98897067 0.94665295]
 [0.85983783 0.15715494 0.90224844]
 [0.3369753  0.64716867 0.52850681]
 [0.54649732 0.49951478 0.0230561 ]
 [0.54510583 0.97619043 0.69954005]
 [0.01155543 0.91500659 0.77325216]]
          0         1         2
0  0.934703  0.833225  0.341831
1  0.702500  0.198414  0.290872
2  0.725317  0.458514  0.494059
3  0.370736  0.538292  0.794845
4  0.004375  0.988971  0.946653
5  0.859838  0.157155  0.902248
6  0.336975  0.647169  0.528507
7  0.546497  0.499515  0.023056
8  0.545106  0.976190  0.699540
9  0.011555  0.915007  0.773252

#### 2 Create a random dataframe containing 3 columns and 10 rows with specific column names. 

Use `['column1', 'column2', 'column3']` as the column names.

In [7]:
df2 = pd.DataFrame(np.random.random((10,3)), columns = ['column1', 'column2', 'column3'])
df2

    column1   column2   column3
0  0.005404  0.619521  0.656104
1  0.629648  0.037413  0.401850
2  0.582297  0.968273  0.415441
3  0.896033  0.958956  0.254968
4  0.740354  0.424801  0.273654
5  0.788799  0.329178  0.788045
6  0.208142  0.277027  0.616849
7  0.574478  0.513601  0.086460
8  0.254989  0.389783  0.226204
9  0.418372  0.490723  0.277804

#### 3 Create a random dataframe containing N columns and M rows with specific column names.

For this task you'll have to name the columns as `['column1', 'column2', 'column3', ...,'columnN']`. You can use a list comprehension to do that.

In [11]:
N = 10
M = 30
list_of_columns = [f'column{number+1}' for number in range(N)]

df3 = pd.DataFrame(data=np.random.random((M,N)), columns = list_of_columns)
df3

,column1,column2,column3,column4,column5,column6,column7,column8,column9,column10
0,0.547366,0.888593,0.871351,0.767691,0.916317,0.599172,0.815745,0.889132,0.339379,0.824921
1,0.665239,0.008172,0.052597,0.249058,0.359730,0.907138,0.028621,0.959015,0.716509,0.177497
2,0.545164,0.955399,0.891313,0.473454,0.640474,0.269838,0.077901,0.705515,0.933251,0.096549
3,0.246498,0.438675,0.656329,0.297877,0.208926,0.167349,0.137630,0.258912,0.730241,0.279344
4,0.973632,0.790932,0.187479,0.035027,0.838714,0.207376,0.233171,0.177798,0.819149,0.491531
5,0.544596,0.666668,0.980371,0.606277,0.161444,0.464101,0.302449,0.421448,0.940212,0.977006
6,0.269923,0.712602,0.350880,0.748319,0.848992,0.775118,0.603120,0.943128,0.850084,0.930930
7,0.665905,0.640432,0.545049,0.946869,0.564259,0.958322,0.342356,0.139960,0.404505,0.452688
8,0.337110,0.006118,0.496687,0.762312,0.402440,0.855358,0.498162,0.525649,0.531974,0.563062
9,0.031351,0.162129,0.298889,0.712523,0.830157,0.742360,0.576794,0.726670,0.074615,0.563287
10,0.795411,0.494661,0.331018,0.857585,0.147147,0.526097,0.955333,0.157086,0.596819,0.460572
11,0.632487,0.813288,0.652762,0.268715,0.005968,0.769774,0.679598,0.057820,0.527001,0.255481
12,0.137230,0.440422,0.073833,0.635904,0.043217,0.969610,0.697665,0.645680,0.691712,0.716985
13,0.561702,0.900797,0.757704,0.799539,0.831613,0.983058,0.693725,0.778531,0.071819,0.244566
14,0.004305,0.639803,0.363455,0.232371,0.104566,0.629840,0.674557,0.655148,0.886589,0.537481
15,0.856174,0.071559,0.866380,0.644463,0.754321,0.041014,0.595887,0.257533,0.225788,0.343917
16,0.430129,0.031599,0.832813,0.965708,0.901627,0.935362,0.964069,0.246619,0.128172,0.713151
17,0.777107,0.224250,0.762183,0.396305,0.105445,0.627624,0.748201,0.177131,0.629200,0.302451
18,0.575921,0.956320,0.922585,0.732163,0.883515,0.649282,0.477169,0.989652,0.130413,0.174119
19,0.233436,0.113423,0.299917,0.242558,0.201397,0.667043,0.608800,0.912208,0.250426,0.707957
20,0.263877,0.772766,0.638809,0.526382,0.101881,0.339712,0.114061,0.652789,0.373380,0.591085
21,0.431810,0.052889,0.150418,0.591616,0.836447,0.860329,0.979136,0.772083,0.626860,0.613097
22,0.355498,0.910450,0.843883,0.789619,0.013285,0.270463,0.931244,0.793010,0.831929,0.989604
23,0.440591,0.035999,0.747433,0.098672,0.278531,0.665134,0.311938,0.236205,0.225150,0.932651
24,0.625218,0.929948,0.886627,0.863835,0.344058,0.929766,0.760216,0.430358,0.934838,0.523181
25,0.942308,0.079457,0.181683,0.929993,0.954301,0.026796,0.130582,0.670129,0.429373,0.314768
26,0.041320,0.114866,0.771059,0.256032,0.128450,0.811780,0.804218,0.328988,0.070888,0.929313
27,0.606056,0.140826,0.071287,0.636785,0.788642,0.312835,0.374560,0.806064,0.133248,0.679276
28,0.985540,0.763253,0.468960,0.079998,0.731539,0.382407,0.476557,0.266006,0.760557,0.107008
29,0.962461,0.052950,0.702823,0.999189,0.787239,0.824037,0.237517,0.009328,0.666313,0.871663